name: Release

on:
  push:
    tags:
      - 'v*'  # v1.0.0과 같은 태그가 푸시될 때 트리거

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Go
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'  # Go 버전 설정

    # 4. Run Goreleaser to build binaries
    - name: Run Goreleaser
      uses: goreleaser/goreleaser-action@v6
          with:
            # either 'goreleaser' (default) or 'goreleaser-pro'
            distribution: goreleaser
            # 'latest', 'nightly', or a semver
            version: "~> v2"
            args: release --clean
      run: goreleaser release --rm-dist

    # 5. Create a zip file of the generated binaries
    - name: Create zip file
      run: |
        mkdir release_assets
        # Assume goreleaser creates binaries in dist/
        for file in dist/*; do
          zip -r release_assets/$(basename "$file").zip "$file"
        done

    # 6. Upload release assets
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: release_assets/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
