name: Release

on:
  push:
    tags:
      - 'test-*' 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Go
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'  # Go 버전 설정

    # 3. GoReleaser Action
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest  # 최신 버전의 GoReleaser 사용
        args: release --rm-dist  # release 명령어에 필요한 인자 전달

    # 4. Upload release assets
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.zip  # GoReleaser에서 생성된 zip 파일 업로드
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
