name: Release

on:
  push:
    tags:
      - 'v*'
permissions: read-all

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write      
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
      - name: Docker Root Dir
        run: docker info | grep "Docker Root Dir"
      - name: Check disk space
        run: du -sh /var/lib/docker
      - name: setup release environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
      - name: release publish
        run: make release

# jobs:
#   release:
#     runs-on: ubuntu-latest

#     steps:
#     # 1. Checkout repository
#     - name: Checkout repository
#       uses: actions/checkout@v3
    
#     # 2. Set up Go
#     - name: Set up Go
#       uses: actions/setup-go@v3
#       with:
#         go-version: '1.22'  # Go 버전 설정

#     - name: Clean dist directory
#       run: rm -rf dist
      
#     - name: Login to GitHub Container Registry
#       uses: docker/login-action@v3
#       with:
#         registry: ghcr.io
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
        
#     - run: git fetch --prune --unshallow
#     - name: setup dependencies
#       uses: actions/setup-go@v2
#     - name: setup release environment
#       run: |-
#         echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
#     - name: release publish
#       run: make release
