name: Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # 2. Set up Go
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'  # Go 버전 설정

    - name: Clean dist directory
      run: rm -rf dist

    - run: git fetch --prune --unshallow
    - name: setup dependencies
      uses: actions/setup-go@v2
    - name: setup release environment
      run: |-
        echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
    - name: release publish
      run: make release

    # 4. Upload release assets
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.zip  # GoReleaser에서 생성된 zip 파일 업로드
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
